project_id = "cqzmrdzwgsujgbjqpoxh"

[functions.hello]
enabled = true
verify_jwt = false

[functions.send-email]
enabled = true
verify_jwt = false

[functions.stripe-payment]
enabled = true
verify_jwt = false

[functions.stripe-webhook]
enabled = true
verify_jwt = false

[functions.stripe-config]
enabled = true
verify_jwt = false

[functions.ai-recommendations]
enabled = true
verify_jwt = false

[functions.receive-email]
enabled = true
verify_jwt = false

[functions.send-class-reminders]
enabled = true
verify_jwt = false

[functions.notify-waitlist]
enabled = true
verify_jwt = false

[functions.process-expired-waitlist]
enabled = true
verify_jwt = false

[functions.process-activation-reminders]
enabled = true
verify_jwt = false

[functions.process-monthly-credits]
enabled = true
verify_jwt = false

[functions.process-freeze-expirations]
enabled = true
verify_jwt = false

[functions.generate-entry-token]
enabled = true
verify_jwt = false

[functions.sync-subscription-status]
enabled = true
verify_jwt = false

[functions.process-session-generation]
enabled = true
verify_jwt = false

[functions.generate-approval-letter]
enabled = true
verify_jwt = false

[functions.process-guest-feedback-emails]
enabled = true
verify_jwt = false

[functions.stripe-failed-invoices]
enabled = true
verify_jwt = false

[functions.send-application-reminder]
enabled = true
verify_jwt = false

[functions.get-autopay-dates]
enabled = true
verify_jwt = false

[functions.send-push-notification]
enabled = true
verify_jwt = false

[functions.stripe-sales-tax]
enabled = true
verify_jwt = false
