// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-membership.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-membership.ts
var get_my_membership_default = defineTool({
  name: "get_my_membership",
  title: "Get my membership",
  description: "Get the signed-in member's Storm Wellness Club membership status, tier, billing dates and past-due flag.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("members").select(
      "member_id, first_name, last_name, email, membership_type, status, membership_start_date, membership_end_date, next_billing_date, payment_past_due, payment_past_due_since"
    ).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No membership record is linked to this account." }],
        structuredContent: { membership: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { membership: data }
    };
  }
});

// src/lib/mcp/tools/list-my-class-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_my_class_bookings_default = defineTool2({
  name: "list_my_class_bookings",
  title: "List my class bookings",
  description: "List the signed-in member's class bookings with session date, time and class name. Defaults to upcoming bookings.",
  inputSchema: {
    include_past: z.boolean().optional().describe("Include bookings for sessions that already happened. Defaults to false."),
    limit: z.number().int().optional().describe("Maximum bookings to return. Defaults to 20, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_past, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("class_bookings").select(
      "id, status, booked_at, cancelled_at, checked_in_at, class_sessions!inner(session_date, start_time, end_time, room, is_cancelled, class_types(name, category))"
    ).order("booked_at", { ascending: false }).limit(max);
    if (!include_past) query = query.gte("class_sessions.session_date", today);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const bookings = (data ?? []).map((b) => {
      const session = b.class_sessions;
      const type = session?.class_types;
      return {
        id: b.id,
        status: b.status,
        checked_in: Boolean(b.checked_in_at),
        class_name: type?.name ?? null,
        category: type?.category ?? null,
        session_date: session?.session_date ?? null,
        start_time: session?.start_time ?? null,
        end_time: session?.end_time ?? null,
        room: session?.room ?? null,
        session_cancelled: session?.is_cancelled ?? false
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(bookings) }],
      structuredContent: { bookings }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-classes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_upcoming_classes_default = defineTool3({
  name: "list_upcoming_classes",
  title: "List upcoming classes",
  description: "List upcoming Storm Wellness Club class sessions with date, time, class name and remaining spots. Booking opens 4 weeks out.",
  inputSchema: {
    days_ahead: z2.number().int().optional().describe("How many days ahead to look. Defaults to 14, max 28."),
    category: z2.string().optional().describe("Optional class category filter, e.g. pilates or cycling."),
    only_available: z2.boolean().optional().describe("Only return sessions with open spots. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, category, only_available }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const days = Math.min(Math.max(days_ahead ?? 14, 1), 28);
    const start = /* @__PURE__ */ new Date();
    const end = new Date(start.getTime() + days * 24 * 60 * 60 * 1e3);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("class_sessions").select(
      "id, session_date, start_time, end_time, room, max_capacity, current_enrollment, is_signature:class_types(name, category, is_signature)"
    ).eq("is_cancelled", false).eq("is_hidden", false).gte("session_date", start.toISOString().slice(0, 10)).lte("session_date", end.toISOString().slice(0, 10)).order("session_date", { ascending: true }).order("start_time", { ascending: true }).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let sessions = (data ?? []).map((s) => {
      const type = s.is_signature;
      const capacity = Number(s.max_capacity ?? 0);
      const enrolled = Number(s.current_enrollment ?? 0);
      return {
        id: s.id,
        class_name: type?.name ?? null,
        category: type?.category ?? null,
        signature: Boolean(type?.is_signature),
        session_date: s.session_date,
        start_time: s.start_time,
        end_time: s.end_time,
        room: s.room,
        spots_left: Math.max(capacity - enrolled, 0),
        max_capacity: capacity
      };
    });
    if (category) {
      const needle = category.trim().toLowerCase();
      sessions = sessions.filter(
        (s) => String(s.category ?? "").toLowerCase().includes(needle) || String(s.class_name ?? "").toLowerCase().includes(needle)
      );
    }
    if (only_available) sessions = sessions.filter((s) => s.spots_left > 0);
    return {
      content: [{ type: "text", text: JSON.stringify(sessions) }],
      structuredContent: { sessions }
    };
  }
});

// src/lib/mcp/tools/list-my-credits.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_credits_default = defineTool4({
  name: "list_my_credits",
  title: "List my credits",
  description: "List the signed-in member's remaining wellness and class credits for the current billing cycle, with expiry dates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("member_credits").select("credit_type, credits_remaining, credits_total, cycle_start, cycle_end, expires_at").gte("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("expires_at", { ascending: true }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const credits = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(credits) }],
      structuredContent: { credits }
    };
  }
});

// src/lib/mcp/tools/list-my-spa-appointments.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_spa_appointments_default = defineTool5({
  name: "list_my_spa_appointments",
  title: "List my spa appointments",
  description: "List the signed-in member's spa and recovery appointments with service, date, time and status. Defaults to upcoming.",
  inputSchema: {
    include_past: z3.boolean().optional().describe("Include past appointments. Defaults to false."),
    limit: z3.number().int().optional().describe("Maximum appointments to return. Defaults to 20, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_past, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("spa_appointments").select(
      "id, service_name, service_category, appointment_date, appointment_time, duration_minutes, status, member_notes"
    ).order("appointment_date", { ascending: true }).limit(max);
    if (!include_past) query = query.gte("appointment_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const appointments = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(appointments) }],
      structuredContent: { appointments }
    };
  }
});

// src/lib/mcp/tools/list-spa-services.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_spa_services_default = defineTool6({
  name: "list_spa_services",
  title: "List spa services",
  description: "List active Storm Wellness Club spa and recovery services with duration, standard price and member price.",
  inputSchema: {
    category: z4.string().optional().describe("Optional category filter, e.g. massage or recovery.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("spa_services").select("id, name, category, description, duration_minutes, price, member_price, popular").eq("is_active", true).order("display_order", { ascending: true }).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let services = data ?? [];
    if (category) {
      const needle = category.trim().toLowerCase();
      services = services.filter((s) => String(s.category ?? "").toLowerCase().includes(needle));
    }
    return {
      content: [{ type: "text", text: JSON.stringify(services) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cqzmrdzwgsujgbjqpoxh";
var mcp_default = defineMcp({
  name: "storm-wellness-hub",
  title: "Storm Wellness Hub",
  version: "0.1.0",
  instructions: "Tools for Storm Wellness Club members. Read the signed-in member's membership status, credits, class bookings and spa appointments, plus the upcoming class schedule and spa service menu. All times are America/Detroit (Michigan Eastern). Class booking opens 4 weeks out.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_membership_default,
    list_my_credits_default,
    list_my_class_bookings_default,
    list_upcoming_classes_default,
    list_my_spa_appointments_default,
    list_spa_services_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
