-- Member Analytics Functions
-- Functions for calculating member lifetime value, attendance patterns, service utilization, churn risk, and engagement scores

-- Function: Calculate Member Lifetime Value (LTV)
-- Returns total revenue generated by a member across all services
CREATE OR REPLACE FUNCTION public.calculate_member_ltv(p_member_id UUID)
RETURNS DECIMAL(10,2)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_ltv DECIMAL(10,2) := 0;
  v_monthly_dues DECIMAL(10,2) := 0;
  v_months_active INTEGER := 0;
BEGIN
  -- Calculate monthly dues based on membership type
  SELECT 
    CASE 
      WHEN membership_type ILIKE '%standard%' THEN 99.00
      WHEN membership_type ILIKE '%premium%' THEN 149.00
      WHEN membership_type ILIKE '%executive%' THEN 199.00
      WHEN membership_type ILIKE '%founder%' THEN 79.00
      ELSE 99.00
    END
  INTO v_monthly_dues
  FROM public.members
  WHERE id = p_member_id;

  -- Calculate months active
  SELECT COALESCE(
    EXTRACT(EPOCH FROM (COALESCE(membership_end_date, CURRENT_DATE) - membership_start_date)) / 2592000,
    0
  )::INTEGER
  INTO v_months_active
  FROM public.members
  WHERE id = p_member_id;

  -- Base LTV = monthly dues * months active
  v_ltv := v_monthly_dues * GREATEST(v_months_active, 0);

  -- Add manual charges
  SELECT COALESCE(SUM(amount), 0) / 100.0
  INTO v_ltv
  FROM public.manual_charges
  WHERE member_id = p_member_id AND status = 'succeeded';

  -- Add spa service payments
  SELECT COALESCE(SUM(COALESCE(member_price, price)), 0)
  INTO v_ltv
  FROM public.spa_appointments
  WHERE member_id = p_member_id AND status = 'completed';

  -- Add cafe orders
  SELECT COALESCE(SUM(total_amount), 0)
  INTO v_ltv
  FROM public.cafe_orders
  WHERE member_id = p_member_id AND status = 'completed';

  RETURN COALESCE(v_ltv, 0);
END;
$$;

-- Function: Get Member Attendance Pattern
-- Returns attendance statistics for a member
CREATE OR REPLACE FUNCTION public.get_member_attendance_pattern(p_member_id UUID, p_days INTEGER DEFAULT 30)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result JSONB;
  v_total_classes INTEGER;
  v_avg_per_week DECIMAL;
  v_preferred_days TEXT[];
  v_preferred_times TEXT[];
BEGIN
  -- Get total classes attended in last N days
  SELECT COUNT(*)
  INTO v_total_classes
  FROM public.member_activities
  WHERE member_id = p_member_id
    AND activity_type = 'class_attended'
    AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL;

  -- Calculate average classes per week
  v_avg_per_week := (v_total_classes::DECIMAL / GREATEST(p_days, 1)) * 7;

  -- Get preferred days of week
  SELECT ARRAY_AGG(DISTINCT day_name)
  INTO v_preferred_days
  FROM (
    SELECT 
      TO_CHAR((activity_data->>'session_date')::date, 'Day') as day_name
    FROM public.member_activities
    WHERE member_id = p_member_id
      AND activity_type = 'class_attended'
      AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    GROUP BY day_name
    ORDER BY COUNT(*) DESC
    LIMIT 3
  ) sub;

  -- Build result JSON
  v_result := jsonb_build_object(
    'total_classes', v_total_classes,
    'period_days', p_days,
    'avg_classes_per_week', ROUND(v_avg_per_week, 2),
    'preferred_days', COALESCE(v_preferred_days, ARRAY[]::TEXT[]),
    'check_ins_count', (
      SELECT COUNT(*)
      FROM public.check_ins
      WHERE member_id = p_member_id
        AND checked_in_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    )
  );

  RETURN v_result;
END;
$$;

-- Function: Get Member Service Utilization
-- Returns statistics on which services a member uses
CREATE OR REPLACE FUNCTION public.get_member_service_utilization(p_member_id UUID, p_days INTEGER DEFAULT 30)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result JSONB;
BEGIN
  v_result := jsonb_build_object(
    'classes_attended', (
      SELECT COUNT(*)
      FROM public.member_activities
      WHERE member_id = p_member_id
        AND activity_type = 'class_attended'
        AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    ),
    'spa_services', (
      SELECT COUNT(*)
      FROM public.member_activities
      WHERE member_id = p_member_id
        AND activity_type = 'spa_service'
        AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    ),
    'cafe_orders', (
      SELECT COUNT(*)
      FROM public.member_activities
      WHERE member_id = p_member_id
        AND activity_type = 'cafe_order'
        AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    ),
    'kids_care_bookings', (
      SELECT COUNT(*)
      FROM public.member_activities
      WHERE member_id = p_member_id
        AND activity_type = 'kids_care_booking'
        AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    ),
    'workouts_logged', (
      SELECT COUNT(*)
      FROM public.member_activities
      WHERE member_id = p_member_id
        AND activity_type = 'workout_logged'
        AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    ),
    'check_ins', (
      SELECT COUNT(*)
      FROM public.check_ins
      WHERE member_id = p_member_id
        AND checked_in_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL
    )
  );

  RETURN v_result;
END;
$$;

-- Function: Calculate Member Churn Risk Score
-- Returns a score from 0-100 indicating churn risk (higher = higher risk)
CREATE OR REPLACE FUNCTION public.calculate_churn_risk(p_member_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_risk_score INTEGER := 0;
  v_days_since_last_visit INTEGER;
  v_days_since_membership_start INTEGER;
  v_total_visits INTEGER;
  v_recent_activity INTEGER;
BEGIN
  -- Get days since last visit
  SELECT COALESCE(
    EXTRACT(EPOCH FROM (CURRENT_DATE - MAX(checked_in_at::date)))::INTEGER,
    999
  )
  INTO v_days_since_last_visit
  FROM public.check_ins
  WHERE member_id = p_member_id;

  -- Get days since membership started
  SELECT COALESCE(
    EXTRACT(EPOCH FROM (CURRENT_DATE - membership_start_date))::INTEGER,
    0
  )
  INTO v_days_since_membership_start
  FROM public.members
  WHERE id = p_member_id;

  -- Get total visits
  SELECT COUNT(*)
  INTO v_total_visits
  FROM public.check_ins
  WHERE member_id = p_member_id;

  -- Get activity in last 30 days
  SELECT COUNT(*)
  INTO v_recent_activity
  FROM public.member_activities
  WHERE member_id = p_member_id
    AND created_at >= CURRENT_DATE - INTERVAL '30 days';

  -- Calculate risk score
  -- Days since last visit (0-50 points)
  IF v_days_since_last_visit > 60 THEN
    v_risk_score := v_risk_score + 50;
  ELSIF v_days_since_last_visit > 30 THEN
    v_risk_score := v_risk_score + 30;
  ELSIF v_days_since_last_visit > 14 THEN
    v_risk_score := v_risk_score + 15;
  END IF;

  -- Recent activity (0-30 points)
  IF v_recent_activity = 0 AND v_days_since_membership_start > 30 THEN
    v_risk_score := v_risk_score + 30;
  ELSIF v_recent_activity < 3 AND v_days_since_membership_start > 60 THEN
    v_risk_score := v_risk_score + 15;
  END IF;

  -- Low total visits for established members (0-20 points)
  IF v_total_visits < 5 AND v_days_since_membership_start > 90 THEN
    v_risk_score := v_risk_score + 20;
  END IF;

  RETURN LEAST(v_risk_score, 100);
END;
$$;

-- Function: Calculate Member Engagement Score
-- Returns a score from 0-100 indicating overall engagement (higher = more engaged)
CREATE OR REPLACE FUNCTION public.calculate_engagement_score(p_member_id UUID, p_days INTEGER DEFAULT 30)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_score INTEGER := 0;
  v_total_activities INTEGER;
  v_unique_days INTEGER;
  v_activity_diversity INTEGER;
BEGIN
  -- Get total activities in period
  SELECT COUNT(*)
  INTO v_total_activities
  FROM public.member_activities
  WHERE member_id = p_member_id
    AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL;

  -- Get unique days with activity
  SELECT COUNT(DISTINCT created_at::date)
  INTO v_unique_days
  FROM public.member_activities
  WHERE member_id = p_member_id
    AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL;

  -- Get activity type diversity
  SELECT COUNT(DISTINCT activity_type)
  INTO v_activity_diversity
  FROM public.member_activities
  WHERE member_id = p_member_id
    AND created_at >= CURRENT_DATE - (p_days || ' days')::INTERVAL;

  -- Calculate score
  -- Activity volume (0-40 points)
  v_score := LEAST((v_total_activities * 2), 40);

  -- Frequency (0-30 points) - unique days / period days
  v_score := v_score + LEAST((v_unique_days::DECIMAL / GREATEST(p_days, 1) * 30)::INTEGER, 30);

  -- Diversity (0-30 points)
  v_score := v_score + LEAST(v_activity_diversity * 6, 30);

  RETURN LEAST(v_score, 100);
END;
$$;



