-- Stage 1: search_path hardening
ALTER FUNCTION public.find_or_create_temp_class_session(_class_name text, _session_date date, _start_time time without time zone, _end_time time without time zone, _max_capacity integer) SET search_path = public;

-- Stage 2: Tighten public bucket listing
DROP POLICY IF EXISTS "Equipment images are publicly accessible" ON storage.objects;
DROP POLICY IF EXISTS "Public can view cafe menu images" ON storage.objects;
DROP POLICY IF EXISTS "Public can view merch images" ON storage.objects;

-- Stage 3: Remove WITH CHECK (true) on write policies
DROP POLICY IF EXISTS "Anyone can submit a service request" ON public.spa_service_requests;
CREATE POLICY "Public intake of service requests" ON public.spa_service_requests FOR INSERT TO anon, authenticated WITH CHECK (email IS NOT NULL AND length(trim(email)) > 3 AND length(coalesce(message,'')) < 5000);

DROP POLICY IF EXISTS "Anyone can submit a training request" ON public.training_requests;
CREATE POLICY "Public intake of training requests" ON public.training_requests FOR INSERT TO anon, authenticated WITH CHECK (email IS NOT NULL AND length(trim(email)) > 3);

DROP POLICY IF EXISTS "Anyone can submit an SMS lead" ON public.sms_marketing_leads;
CREATE POLICY "Public intake of SMS leads" ON public.sms_marketing_leads FOR INSERT TO anon, authenticated WITH CHECK (phone IS NOT NULL AND length(trim(phone)) >= 10);

DROP POLICY IF EXISTS "Service role manages class achievements" ON public.user_class_achievements;
CREATE POLICY "Service role manages class achievements" ON public.user_class_achievements FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Stage 4: SECURITY DEFINER EXECUTE lockdown
REVOKE EXECUTE ON FUNCTION public.adjust_cafe_credit(_member_id uuid, _amount_cents integer, _reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_cancel_class_session(_session_id uuid, _is_hidden boolean, _cancellation_reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_cancel_kids_care_booking(p_booking_id uuid, p_cancellation_reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_clear_staff_pin(_staff_user_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_create_kids_care_booking(p_user_id uuid, p_member_id uuid, p_child_name text, p_child_age integer, p_booking_date date, p_start_time time without time zone, p_end_time time without time zone, p_pass_id uuid, p_special_instructions text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_link_member_to_user(_member_id uuid, _user_email text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_mark_instructor_invited(_instructor_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_set_staff_pin(_staff_user_id uuid, _pin text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_assign_staff_roles_on_signup() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_claim_mothers_day_packs() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_fulfill_import_on_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_fulfill_pending_import() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_link_member_on_profile_create() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_link_non_member_on_signup() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.award_class_milestones(p_booking_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.award_referral_points(_referring_member_id uuid, _referred_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.block_kids_care_booking_if_past_due() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.book_pt_appointment(p_user_id uuid, p_format pt_format, p_starts_at timestamp with time zone, p_duration_minutes integer, p_instructor_id uuid, p_notes text, p_pass_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.book_wellness_appointment(p_service_id text, p_service_name text, p_service_category text, p_service_price numeric, p_appointment_date date, p_appointment_time time without time zone, p_duration_minutes integer, p_cleanup_minutes integer, p_credit_type text, p_member_notes text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_churn_risk(p_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_engagement_score(p_member_id uuid, p_days integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_health_score(_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_member_ltv(p_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.can_manage_staff_schedule(_user_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_class_booking(_booking_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_pt_appointment(p_appointment_id uuid, p_reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_and_award_achievements(_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_for_duplicate_check_in(p_member_id uuid, p_check_in_window_minutes integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_goal_milestones(_goal_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_referral_on_member_activation() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.check_spa_appointment_conflict(p_appointment_date date, p_appointment_time time without time zone, p_duration_minutes integer, p_cleanup_minutes integer, p_staff_id uuid, p_room_id uuid, p_exclude_appointment_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_mothers_day_pack(_email text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_atomic_class_booking(_session_id uuid, _user_id uuid, _payment_method text, _member_credit_id uuid, _pass_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_fundraiser_class_booking(_session_id uuid, _user_id uuid, _amount_cents integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_spa_review_token_on_complete() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.current_user_email() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.current_user_email_lower() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_application_payment_method() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.ensure_spa_review_token(_appointment_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.evaluate_member_check_in_eligibility(p_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.find_or_create_temp_class_session(_class_name text, _session_date date, _start_time time without time zone, _end_time time without time zone, _max_capacity integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.frontdesk_auto_close_stale_shifts() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.frontdesk_clock_in(_pin text, _device_label text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.frontdesk_clock_out(_pin text, _device_label text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.frontdesk_open_shifts() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.frontdesk_staff_roster() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_class_sessions(_start_date date, _weeks_ahead integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_referral_code(_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_shifts_from_templates(week_start date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_admin_kids_care_bookings(p_booking_date date, p_date_from date, p_date_to date, p_status text, p_member_id uuid, p_age_group text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_all_class_type_ratings() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_all_spa_service_ratings() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_class_reviews_with_names(_class_type_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_class_type_ratings(_class_type_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_dunning_efficiency(p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_instructors_with_contact() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_member_arrears_summary(p_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_member_attendance_pattern(p_member_id uuid, p_days integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_member_cafe_credit_balance(_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_member_payment_history(p_member_id uuid, p_limit integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_member_service_utilization(p_member_id uuid, p_days integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_next_waitlist_position(p_session_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_payment_metrics(p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_pending_class_milestone() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_pending_spa_reviews() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_public_instructors() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_public_spa_therapists() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_scheduled_functions_config() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_spa_review_token_info(_token uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_spa_reviews_with_names(_service_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_spa_therapists_with_contact() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_subscription_health() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_therapist_payroll(_therapist_id uuid, _start_date date, _end_date date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_waitlist_counts(p_session_ids uuid[]) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.grant_cafe_cash_credit(_member_id uuid, _amount_cents integer, _reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.grant_cafe_prepaid_items(_member_id uuid, _menu_item_id uuid, _quantity integer, _reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_any_role(_user_id uuid, _roles app_role[]) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_any_staff_role(_user_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.import_marketing_contacts(rows jsonb, _source_label text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_admin(_user_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_email_blocked(p_email text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_member_past_due(p_member_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.join_waitlist_with_hold(p_session_id uuid, p_method text, p_pass_id uuid, p_credit_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_check_in_class(p_booking_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_check_in_guest(p_guest_pass_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_check_in_kids_care(p_booking_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_check_in_member(p_member_id_text text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_check_in_spa(p_spa_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_check_out_kids_care(p_booking_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_class_roster(p_session_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_kids_care_roster(p_booking_date date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_search_visitors(p_query text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.kiosk_todays_attendance() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.link_instructor_on_signup() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.link_member_by_email() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.link_mothers_day_vouchers_to_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_amenity_usage_activity() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_cafe_order() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_payment_attempt(p_member_id uuid, p_stripe_invoice_id text, p_stripe_payment_intent_id text, p_stripe_charge_id text, p_stripe_subscription_id text, p_invoice_number text, p_amount numeric, p_currency text, p_status text, p_attempt_number integer, p_payment_method_id text, p_payment_method_type text, p_failure_code text, p_failure_message text, p_decline_code text, p_decline_reason text, p_retry_attempted boolean, p_next_retry_at timestamp with time zone, p_succeeded_at timestamp with time zone, p_failed_at timestamp with time zone, p_metadata jsonb) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_spa_service() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.lookup_mothers_day_voucher(p_code text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_class_milestones_seen() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_guest_pass_used(p_pass_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_member_achievement_celebrated(_achievement_id uuid, _achievement_type text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_superseded_failed_attempts() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.move_class_booking(p_booking_id uuid, p_target_session_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_non_member_for_active_member() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.preview_marketing_contacts(rows jsonb) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.process_member_scan(p_member_id_text text, p_scanned_by uuid, p_auto_check_in boolean, p_device_type text, p_override boolean, p_override_reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.recompute_marketing_contact_segment(_email text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.reconcile_and_generate_class_sessions(_start_date date, _weeks_ahead integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.record_cafe_cash_purchase(_member_id uuid, _amount_cents integer, _payment_intent_id text, _reason text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.redeem_cafe_credit(_member_id uuid, _cafe_order_id uuid, _cart_items jsonb, _cash_to_apply_cents integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.redeem_guest_pass_credit(p_guest_first_name text, p_guest_last_name text, p_guest_email text, p_guest_phone text, p_visit_date date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.redeem_mothers_day_voucher(p_code text, p_appointment_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.redeem_referral_points(_member_id uuid, _reward_type text, _points_cost integer) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.refund_waitlist_hold(p_waitlist_id uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_kiosk_pin(p_pin text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.staff_book_wellness_appointment(p_member_id uuid, p_credit_type text, p_appointment_date date, p_appointment_time time without time zone, p_staff_notes text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_class_review(_booking_id uuid, _class_type_id uuid, _session_id uuid, _rating integer, _review_text text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_class_review_for_booking(_booking_id uuid, _rating integer, _review_text text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_public_spa_review(_service_id uuid, _therapist_id uuid, _rating integer, _review_text text, _display_name text, _email text, _honeypot text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_spa_review_via_token(_token uuid, _rating integer, _review_text text, _display_name text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_marketing_contact_from_member() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_marketing_contact_from_non_member() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_non_member_profile_from_profiles() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_phone_applications_to_profiles() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_phone_members_to_profiles() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_schedule_active_to_sessions() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.track_payment_method_update(p_member_id uuid, p_payment_method_id text, p_event_type text, p_card_last4 text, p_card_brand text, p_card_exp_month integer, p_card_exp_year integer, p_is_default boolean) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_auto_award_achievements() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_award_class_milestones() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_session_enrollment() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_spa_appointment_admin(p_appointment_id uuid, p_service_id text, p_service_name text, p_service_category text, p_service_price numeric, p_member_price numeric, p_duration_minutes integer, p_cleanup_minutes integer, p_appointment_date date, p_appointment_time time without time zone, p_staff_id uuid, p_room_id uuid, p_staff_notes text, p_override_conflict boolean) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_subscription_status_with_history(p_member_id uuid, p_new_status text, p_change_reason text, p_stripe_event_id text, p_changed_by text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.use_pt_session(_pass_id uuid, _notes text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_manager_refund_code(_code text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.verify_kiosk_pin(p_pin text) FROM PUBLIC, anon, authenticated;

-- Re-grant EXECUTE to authenticated for client-callable functions
GRANT EXECUTE ON FUNCTION public.adjust_cafe_credit(_member_id uuid, _amount_cents integer, _reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cancel_class_session(_session_id uuid, _is_hidden boolean, _cancellation_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cancel_kids_care_booking(p_booking_id uuid, p_cancellation_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_clear_staff_pin(_staff_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_kids_care_booking(p_user_id uuid, p_member_id uuid, p_child_name text, p_child_age integer, p_booking_date date, p_start_time time without time zone, p_end_time time without time zone, p_pass_id uuid, p_special_instructions text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_link_member_to_user(_member_id uuid, _user_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_staff_pin(_staff_user_id uuid, _pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.book_pt_appointment(p_user_id uuid, p_format pt_format, p_starts_at timestamp with time zone, p_duration_minutes integer, p_instructor_id uuid, p_notes text, p_pass_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.book_wellness_appointment(p_service_id text, p_service_name text, p_service_category text, p_service_price numeric, p_appointment_date date, p_appointment_time time without time zone, p_duration_minutes integer, p_cleanup_minutes integer, p_credit_type text, p_member_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_churn_risk(p_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_engagement_score(p_member_id uuid, p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_health_score(_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_member_ltv(p_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_staff_schedule(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_class_booking(_booking_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_pt_appointment(p_appointment_id uuid, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_and_award_achievements(_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_goal_milestones(_goal_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_spa_appointment_conflict(p_appointment_date date, p_appointment_time time without time zone, p_duration_minutes integer, p_cleanup_minutes integer, p_staff_id uuid, p_room_id uuid, p_exclude_appointment_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_mothers_day_pack(_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_atomic_class_booking(_session_id uuid, _user_id uuid, _payment_method text, _member_credit_id uuid, _pass_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_email() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_email_lower() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_spa_review_token(_appointment_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.frontdesk_auto_close_stale_shifts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.frontdesk_clock_in(_pin text, _device_label text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.frontdesk_clock_out(_pin text, _device_label text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.frontdesk_open_shifts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.frontdesk_staff_roster() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_class_sessions(_start_date date, _weeks_ahead integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_referral_code(_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_shifts_from_templates(week_start date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_kids_care_bookings(p_booking_date date, p_date_from date, p_date_to date, p_status text, p_member_id uuid, p_age_group text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_all_class_type_ratings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_all_spa_service_ratings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_class_reviews_with_names(_class_type_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_class_type_ratings(_class_type_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_dunning_efficiency(p_start_date timestamp with time zone, p_end_date timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_instructors_with_contact() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_member_arrears_summary(p_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_member_attendance_pattern(p_member_id uuid, p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_member_cafe_credit_balance(_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_member_payment_history(p_member_id uuid, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_member_service_utilization(p_member_id uuid, p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_next_waitlist_position(p_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_payment_metrics(p_start_date timestamp with time zone, p_end_date timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pending_class_milestone() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pending_spa_reviews() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_instructors() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_spa_therapists() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_spa_review_token_info(_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_spa_reviews_with_names(_service_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_spa_therapists_with_contact() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_subscription_health() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_therapist_payroll(_therapist_id uuid, _start_date date, _end_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_waitlist_counts(p_session_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_cafe_cash_credit(_member_id uuid, _amount_cents integer, _reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_cafe_prepaid_items(_member_id uuid, _menu_item_id uuid, _quantity integer, _reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_any_role(_user_id uuid, _roles app_role[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_any_staff_role(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.import_marketing_contacts(rows jsonb, _source_label text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_email_blocked(p_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_member_past_due(p_member_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.join_waitlist_with_hold(p_session_id uuid, p_method text, p_pass_id uuid, p_credit_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_check_in_class(p_booking_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_check_in_guest(p_guest_pass_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_check_in_kids_care(p_booking_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_check_in_member(p_member_id_text text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_check_in_spa(p_spa_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_check_out_kids_care(p_booking_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_class_roster(p_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_kids_care_roster(p_booking_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_search_visitors(p_query text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.kiosk_todays_attendance() TO authenticated;
GRANT EXECUTE ON FUNCTION public.link_member_by_email() TO authenticated;
GRANT EXECUTE ON FUNCTION public.lookup_mothers_day_voucher(p_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_class_milestones_seen() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_guest_pass_used(p_pass_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_member_achievement_celebrated(_achievement_id uuid, _achievement_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.move_class_booking(p_booking_id uuid, p_target_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_marketing_contacts(rows jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_member_scan(p_member_id_text text, p_scanned_by uuid, p_auto_check_in boolean, p_device_type text, p_override boolean, p_override_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reconcile_and_generate_class_sessions(_start_date date, _weeks_ahead integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_cafe_cash_purchase(_member_id uuid, _amount_cents integer, _payment_intent_id text, _reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_cafe_credit(_member_id uuid, _cafe_order_id uuid, _cart_items jsonb, _cash_to_apply_cents integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_guest_pass_credit(p_guest_first_name text, p_guest_last_name text, p_guest_email text, p_guest_phone text, p_visit_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_mothers_day_voucher(p_code text, p_appointment_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_referral_points(_member_id uuid, _reward_type text, _points_cost integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refund_waitlist_hold(p_waitlist_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_kiosk_pin(p_pin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.staff_book_wellness_appointment(p_member_id uuid, p_credit_type text, p_appointment_date date, p_appointment_time time without time zone, p_staff_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_class_review(_booking_id uuid, _class_type_id uuid, _session_id uuid, _rating integer, _review_text text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_class_review_for_booking(_booking_id uuid, _rating integer, _review_text text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_public_spa_review(_service_id uuid, _therapist_id uuid, _rating integer, _review_text text, _display_name text, _email text, _honeypot text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_spa_review_via_token(_token uuid, _rating integer, _review_text text, _display_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_spa_appointment_admin(p_appointment_id uuid, p_service_id text, p_service_name text, p_service_category text, p_service_price numeric, p_member_price numeric, p_duration_minutes integer, p_cleanup_minutes integer, p_appointment_date date, p_appointment_time time without time zone, p_staff_id uuid, p_room_id uuid, p_staff_notes text, p_override_conflict boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.use_pt_session(_pass_id uuid, _notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_manager_refund_code(_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_kiosk_pin(p_pin text) TO authenticated;

-- Re-grant EXECUTE to anon for unauthenticated public flows
GRANT EXECUTE ON FUNCTION public.ensure_spa_review_token(_appointment_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_all_class_type_ratings() TO anon;
GRANT EXECUTE ON FUNCTION public.get_all_spa_service_ratings() TO anon;
GRANT EXECUTE ON FUNCTION public.get_class_reviews_with_names(_class_type_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_class_type_ratings(_class_type_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_instructors() TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_spa_therapists() TO anon;
GRANT EXECUTE ON FUNCTION public.get_spa_review_token_info(_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_spa_reviews_with_names(_service_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.has_any_role(_user_id uuid, _roles app_role[]) TO anon;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO anon;
GRANT EXECUTE ON FUNCTION public.is_email_blocked(p_email text) TO anon;
GRANT EXECUTE ON FUNCTION public.kiosk_search_visitors(p_query text) TO anon;
GRANT EXECUTE ON FUNCTION public.lookup_mothers_day_voucher(p_code text) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_public_spa_review(_service_id uuid, _therapist_id uuid, _rating integer, _review_text text, _display_name text, _email text, _honeypot text) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_spa_review_via_token(_token uuid, _rating integer, _review_text text, _display_name text) TO anon;